<?php return array (
  'title' => 'Shoot A Mail',
  'tagline' => '',
  'description' => '',
  'keyword' => '',
  'editor' => 'Admin',
  'company' => 'Shoot A Mail',
  'address' => '',
  'latitude' => '',
  'longitude' => '',
  'phone' => '',
  'fax' => '',
  'email' => '',
  'copyright' => '',
  'og_image' => 'images/og-default.jpg',
  'fb_like_page' => '',
  'twitter_page' => '',
  'google' => '',
  'youtube' => '',
  'linkedin' => '',
  'pinterest' => '',
  'tv' => '',
  'fb_app_id' => '',
);