<?php return array (
  'title' => 'AOR',
  'tagline' => 'Agent Of Recruitment',
  'description' => 'Agent Of Recruitment',
  'keyword' => '',
  'editor' => 'Admin',
  'company' => 'COMPANY',
  'address' => '',
  'phone' => '',
  'fax' => '',
  'email' => '',
  'copyright' => '',
  'og_image' => 'images/og-default.jpg',
  'fb_like_page' => '',
  'twitter_page' => '',
  'google' => '',
  'youtube' => '',
  'linkedin' => '',
  'pinterest' => '',
  'tv' => '',
  'fb_app_id' => '',
);